name: Manually triggered Docker build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker tag'
        required: true
        
jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      #- name: Reclaim disk space
      #  run: |
      #    sudo chmod u+x reclaim_disk_space.sh
      #    ./reclaim_disk_space.sh
      #  working-directory: ${{ github.workspace }}/.github/workflows/script/
      
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
        
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/${{ github.event.inputs.tag }}

